version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: warsimuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: warsimapp
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warsimuser -d warsimapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: always
    environment:
      DB_USER: warsimuser
      DB_PASSWORD: mypassword
      DB_NAME: warsimapp
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ADMIN_EMAIL: admin@war-simulation.com
      ADMIN_PASSWORD: adminpassword
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data:
  redis_data:
